version: '3'
services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
    container_name: es01
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic

  kib01:
    image: docker.elastic.co/kibana/kibana:7.9.2
    container_name: kib01
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_URL: http://es01:9200
      ELASTICSEARCH_HOSTS: http://es01:9200
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.9.2
    volumes:
    #   - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./elastic/logstash/pipeline:/usr/share/logstash/pipeline:ro
    restart: always
    ports:
      - "5000:5000"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
      ES_HOST: "es01"
      ES_PORT: "9200"
      JIRA_BASE_PATH: ${JIRA_BASE_PATH}
      JIRA_PROJECT: ${JIRA_PROJECT}
      JIRA_USER: ${JIRA_USER}
      JIRA_PASSWORD: ${JIRA_PASSWORD}
      JIRA_MAX_RESULT: 1
    networks:
      - elastic

volumes:
  data01:
    driver: local

networks:
  elastic:
    driver: bridge